src/Entity/Emprunt.php
<?php

namespace App\Entity;

use App\Repository\EmpruntRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmpruntRepository::class)
 */
class Emprunt
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Livre::class, inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $livre;

    /**
     * @ORM\ManyToOne(targetEntity=Abonne::class, inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $abonne;

    /**
     * @ORM\Column(type="date")
     */
    private $date_emprunt;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_retour;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): self
    {
        $this->livre = $livre;

        return $this;
    }

    public function getAbonne(): ?Abonne
    {
        return $this->abonne;
    }

    public function setAbonne(?Abonne $abonne): self
    {
        $this->abonne = $abonne;

        return $this;
    }

    public function getDateEmprunt(): ?\DateTimeInterface
    {
        return $this->date_emprunt;
    }

    public function setDateEmprunt(\DateTimeInterface $date_emprunt): self
    {
        $this->date_emprunt = $date_emprunt;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(?\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Emprunt;
use App\Repository\LivreRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/profil")
 *
 */

class ProfilController extends AbstractController
{
    /**
     * @Route("/", name="profil")
     *
     */
    public function index(): Response
    {
        return $this->render('profil/index.html.twig');
    }
    /**
     * @Route("/profil/newEmprunt{id}", name="profil_new_emprunt")
     *
     */
    public function newEmprunt(LivreRepository $livreRepository, $id): Response
    {
        $user = $this->getUser();
        $livre = $livreRepository->find($id);
        $date = new \DateTime();

        $emprunt = new Emprunt();
        $emprunt->setDateEmprunt($date);
        $emprunt->setLivre($livre);
        $emprunt->setAbonne($user);
        
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($emprunt);
        $entityManager->flush();
        $this->addFlash("success", "Emprunt confirmé");
        return $this->redirectToRoute('profil');
    }
}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Profil
{% endblock %}

{% block body %}

	<ul class="list-group">
		<li class="list-group-item">
			<strong>ID :
			</strong>
			{{app.user.id}}
		</li>
		<li class="list-group-item">
			<strong>Pseudo :
			</strong>
			{{app.user.pseudo}}
		</li>
		<li class="list-group-item">
			<strong>Nom :
			</strong>
			{{app.user.nom}}
		</li>
		<li class="list-group-item">
			<strong>Prénom :
			</strong>
			{{app.user.prenom}}
		</li>
		<li class="list-group-item">
			<strong>Statut :
			</strong>
			{% for role in app.user.roles %}
				{% if role == "ROLE_ADMIN" %}
					Administrateur
				{% elseif role == "ROLE_BIBLIOTHECAIRE" %}
					Bibliothécaire
				{% elseif role == "ROLE_ABONNE" %}
					Abonné
				{% else %}
					Lecteur
				{% endif %}
			{% endfor %}
		</li>
	</ul>

	<table class="table">
		<thead>
			<tr>
				<th>Livre</th>
				<th>Emprunté le : </th>
				<th>Retourné le : </th>
			</tr>
		</thead>
		<tbody>
			{% for emprunt in app.user.emprunts %}
				<tr>
					<td>{{emprunt.livre.titre ~ " - " ~ emprunt.livre.auteur }}</td>
					<td>{{emprunt.dateEmprunt|date("d/m/y")}}</td>
					<td>{{emprunt.dateRetour ? emprunt.dateRetour|date("d/m/y") : "à rendre"}}</td>	
				{% endfor %}
				</tr>
			</tbody>
		</tbody>
	</table>
{% endblock %}